version: "3.9"

services:
  backend:
    build: .
    container_name: sjs_backend_dev

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped

    command: npm run dev